### PR TITLE
✨ Add include support

### PR DESCRIPTION
**Pull request by josemac95**
### Changes

- ✨  Added support for `#include` directive.
	- Source code based on https://github.com/ricardomatias/esbuild-plugin-glsl-include.
- ✅ Added test support for `#include` directive.

Feel free to edit whatever you want, I'm no expert in `TypeScript` or `Ava`, but I've checked that it works for me.

### CODE REVIEW

**Comment by markets** [comment]
Hello @vanruesc, what do you think about this change? If you don't like it, we're going to continue with our fork. We think this is a good enhancement for the project and we'd like it to upstream the patch, but of course if you don't want/need this feature we are ok to continue with our custom fork. Let us know what you think.

Thanks!

**Comment by vanruesc** [comment]
Hi, thanks for contributing!

I think this is a nice feature and the PR looks good. However, the syntax seems a bit too similar to `three`'s include system (`#include <shader_chunk>`). I'm not sure if this would be a problem though; need to think about it. We could consider an alternative include syntax to reduce ambiguity or we could add a setting like `resolveIncludes` to let the user opt into the new behaviour :thinking:

**Comment by josemac95** [comment]
Hi @vanruesc, it's a pleasure to contribute!

The include pattern used by `ThreeJS` is `/^[ \t]*#include +<([\w\d./]+)>/gm`. It's very similar to the one we are using, but the main difference is that they use `<` and `>` instead of `"` or `'` as we do.

I've updated the regular expression to make it:
- More robust. Like `ThreeJS`, more spaces are allowed between `#include` and `"` or `'`.
- Less redundant. `\w` already contains `_`.
- Case sensitive.

About the ambiguity, unless `ThreeJs` changes its pattern, I think there should be no problem because the patterns do not overlap. In fact, as far as I've seen, they are at different stages of the pipeline and our `#include` is processed before the `ThreeJS`'s `#include`.

**Comment by vanruesc** [comment]
> In fact, as far as I've seen, they are at different stages of the pipeline and our #include is processed before the three's #include.

Right, but that's just a coincidence. If someone else had a custom shader include system in place that used `"` instead, then this new behaviour would break their code. This feature introduces potential conflicts that wouldn't otherwise exist.

I'll merge this anyway because it's useful, but I'll add an option to disable the feature.

**Comment by josemac95** [comment]
Hi @vanruesc, I want to use this new feature but I think that it won't be available until you make a release. I thought I could reference this repository instead of the `npm package` as below:

```
"esbuild-plugin-glsl": "https://github.com/vanruesc/esbuild-plugin-glsl.git",
```

However, as there is no `dist` folder it doesn't work. What is the best approach in your opinion?

**Comment by vanruesc** [comment]
Sorry for the delay! The changes are now included in `esbuild-plugin-glsl@1.2.0`.

**Comment by vanruesc** [comment]
The unit test works as expected :thinking:  Can you specify what doesn't work exactly?

**Comment by josemac95** [comment]
Oops sorry, I didn't see your reply and created the PR. Check it out if you want or feel free to do it by yourself @vanruesc!
- #8

**Comment by vanruesc** [comment]
Should be fixed in `esbuild-plugin-glsl@1.2.1`.

I've also updated the unit test to catch this use case and noticed another bug that would sometimes cause the test to fail because the regular expressions weren't reset properly after the refactoring.

**Comment by josemac95** [comment]
Yes, it works like a charm, thanks for the effort!

**Pull request merged**
